force-app/main/default/objects/Name__c/Name__c.object-meta.xml
<CustomObject>
    <description>It&apos;s just a name.</description>
    <label>Name</label>
    <nameField>
        <label>Fullname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Name__c/fields/Number1__c.field-meta.xml
<CustomField>
    <fullName>Number1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Name__c/fields/Number2__c.field-meta.xml
<CustomField>
    <fullName>Number2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Name__c/fields/Output__c.field-meta.xml
<CustomField>
    <fullName>Output__c</fullName>
    <label>Output</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CopyNameTest.cls
@isTest
public class CopyNameTest {
    @isTest
    private static void TestCopyName() {
        Name__c obj = new Name__c();
        obj.Name = 'Dhruvin';
        obj.Number1__c = 10.37;
        obj.Number2__c = -3.2;
        
        insert obj;
        Name__c newObj = [SELECT Output__c, Total__c FROM Name__c WHERE Id = :obj.Id];
        System.assertEquals(obj.Name, newObj.Output__c);
        System.assertEquals(7.17, newObj.Total__c );
        
        obj.Number2__c = null;
        update obj;
        Name__c updatedObj = [SELECT Output__c, Total__c FROM Name__c WHERE Id = :obj.Id];
        System.assertEquals(10.37, updatedObj.Total__c);
        
        delete obj;
    }
}